---
- name: Configure mongodb
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Change mongo config file
      template:
        src: templates/mongodb.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      tags: db-tag
      notify: restart mongodb

    - name: Set variable to file with ip mongodb
      become: false
      local_action:
        module: copy
        content: "db_host: {{ hostvars['dbserver']['ansible_all_ipv4_addresses'][0] }}"
        dest: vars/env.yml.bak

  handlers:
    - name: restart mongodb
      service: name=mongodb state=restarted

- name: Configure app
  hosts: app
  become: true
  tags: app-tag
  vars_files:
    - vars/env.yml.bak

  tasks:
    - name: Add to config for DB connect
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config

    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service

    - name: enable puma
      systemd: name=puma enabled=yes
      notify: reload puma

  handlers:
    - name: reload puma
      systemd: name=puma state=reloaded

- name: Deploy app
  hosts: app
  become: true
  tags: deploy-tag

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit
      notify: restart puma

  handlers:
    - name: restart puma
      systemd: name=puma state=restarted
